### ISSUE TITLE
"Scenario: Parallel" fails randomly

### ISSUE THREAD

**Issue by chrislwade** [patterns-group/code-patterns#131]
Due to the nature of the test and the implementation of `Parallel.ForEach` this test will fail at random if the CLR decides to use a single thread to process the entire list.

A possible fix for the test would be to simply perform both a parallel and serial run, time both, and ensure the parallel execution time was lower.  This would require that both the parallel and serial operation sleep during each iteration.

This could still fail if the CLR decides to use a single thread but the sleeps should induce the CLR to chose to re-partition the list and iterate it across more threads.

**Comment by ghost** [comment]
Without doing things that assume knowledge of the CLR, there's no clear method of testing this.

-- Posted by my alternate account.

**Comment by jbatte47** [comment]
As his Advocate, I feel obliged to tell you that the Devil said: _"Isn't the whole point of an assertion like this to test an assumption made about a specific aspect of the CLR? Namely, its tendency to use auxiliary threads to execute tasks when run through the Parallelization framework? In fact, the point of the API being abstracted here (`Parallel.ForEach`) is to hide that kind of knowledge from the consumer. Once you've hooked into the `Parallel` type, all you know is your application is going to run its logic through a task manager. In most cases that's all the information that's needed to proceed and so life moves on. Testing to make sure that some sort of optimization is occurring is testing the CLR."_

To add to what the dark one had to say, I would say that we definitely don't want to get into the business of testing the CLR, because then we'll never get out of here. Maybe we should just delete the test. Sounds like you'd be on board with that...

One particularly crazy alternative would be to use some very sneaky, hacky code to inject our logic where it doesn't belong in the .NET callstack, and hook into those interception points to gain some awareness of which CLR pathway was taken during a particular test run. That, again, is the kind of micromanagement of an implementation's details that will only cause horrible pain and pressure from all the bloating later on.

![Oop! There I go!](http://img2.wikia.nocookie.net/__cb20120711002559/disney/images/f/f1/1000px-Bloat-FindingNemo3D.jpg)

**Comment by chrislwade** [comment]
I am onboard with removing this test until it's possible to mock static methods natively.  That's the proper test -- mock `Parallel.ForEach` to simply ensure it was called.

Closed because the test can be re-run to prove the code does work.  It's personal choice at this point.
